### ISSUE TITLE
Invalid Range exceptions

### ISSUE THREAD

**Issue by adamw** [softwaremill/adopt-tapir#138]
The following keeps up popping up in the logs:

```
java.lang.RuntimeException: Invalid Range
    at sttp.tapir.DecodeResult$.fromEitherString(DecodeResult.scala:51)
    at sttp.tapir.Codec$.$anonfun$range$1(Codec.scala:508)
    at sttp.tapir.Mapping$$anon$4.rawDecode(Mapping.scala:59)
    at sttp.tapir.Codec$$anon$1.$anonfun$rawDecode$1(Codec.scala:74)
    at sttp.tapir.DecodeResult$Value.flatMap(DecodeResult.scala:15)
    at sttp.tapir.Codec$$anon$1.rawDecode(Codec.scala:74)
    at sttp.tapir.Codec.$anonfun$decode$1(Codec.scala:62)
    at sttp.tapir.Mapping$.$anonfun$decode$3(Mapping.scala:94)
    at scala.util.Try$.apply(Try.scala:210)
    at sttp.tapir.Mapping$.tryRawDecode$1(Mapping.scala:94)
    at sttp.tapir.Mapping$.decode(Mapping.scala:113)
    at sttp.tapir.Codec.decode(Codec.scala:62)
    at sttp.tapir.Codec.decode$(Codec.scala:62)
    at sttp.tapir.Codec$$anon$1.decode(Codec.scala:73)
    at sttp.tapir.Codec$.$anonfun$listBinary$2(Codec.scala:386)
    at scala.collection.immutable.List.map(List.scala:246)
    at sttp.tapir.Codec$.$anonfun$listBinary$1(Codec.scala:386)
    at sttp.tapir.Mapping$$anon$4.rawDecode(Mapping.scala:59)
    at sttp.tapir.Codec$$anon$1.$anonfun$rawDecode$1(Codec.scala:74)
    at sttp.tapir.DecodeResult$Value.flatMap(DecodeResult.scala:15)
    at sttp.tapir.Codec$$anon$1.rawDecode(Codec.scala:74)
    at sttp.tapir.Codec$$anon$1.rawDecode(Codec.scala:74)
    at sttp.tapir.Codec.$anonfun$decode$1(Codec.scala:62)
    at sttp.tapir.Mapping$.$anonfun$decode$3(Mapping.scala:94)
    at scala.util.Try$.apply(Try.scala:210)
    at sttp.tapir.Mapping$.tryRawDecode$1(Mapping.scala:94)
    at sttp.tapir.Mapping$.decode(Mapping.scala:113)
    at sttp.tapir.Codec.decode(Codec.scala:62)
    at sttp.tapir.Codec.decode$(Codec.scala:62)
    at sttp.tapir.Codec$$anon$1.decode(Codec.scala:73)
    at sttp.tapir.Codec$$anon$2.rawDecode(Codec.scala:92)
    at sttp.tapir.Codec.$anonfun$decode$1(Codec.scala:62)
    at sttp.tapir.Mapping$.$anonfun$decode$3(Mapping.scala:94)
    at scala.util.Try$.apply(Try.scala:210)
    at sttp.tapir.Mapping$.tryRawDecode$1(Mapping.scala:94)
    at sttp.tapir.Mapping$.decode(Mapping.scala:113)
    at sttp.tapir.Codec.decode(Codec.scala:62)
    at sttp.tapir.Codec.decode$(Codec.scala:62)
    at sttp.tapir.Codec$$anon$2.decode(Codec.scala:91)
    at sttp.tapir.server.interpreter.DecodeBasicInputs$.matchOther(DecodeBasicInputs.scala:305)
    at sttp.tapir.server.interpreter.DecodeBasicInputs$.matchOthers(DecodeBasicInputs.scala:251)
    at sttp.tapir.server.interpreter.DecodeBasicInputs$.$anonfun$apply$8(DecodeBasicInputs.scala:108)
    at sttp.tapir.server.interpreter.DecodeBasicInputs$.$anonfun$compose$1(DecodeBasicInputs.scala:340)
    at sttp.tapir.server.interpreter.DecodeBasicInputs$.$anonfun$compose$1(DecodeBasicInputs.scala:341)
    at sttp.tapir.server.interpreter.DecodeBasicInputs$.$anonfun$compose$1(DecodeBasicInputs.scala:341)
    at sttp.tapir.server.interpreter.DecodeBasicInputs$.apply(DecodeBasicInputs.scala:109)
    at sttp.tapir.server.interpreter.ServerInterpreter.tryServerEndpoint(ServerInterpreter.scala:95)
    at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$firstNotNone$1(ServerInterpreter.scala:54)
    at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:61)
    at sttp.tapir.server.interpreter.ServerInterpreter.firstNotNone(ServerInterpreter.scala:56)
    at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$callInterceptors$1(ServerInterpreter.scala:31)
    at sttp.tapir.server.interceptor.RequestHandler$$anon$1.apply(RequestHandler.scala:16)
    at sttp.tapir.server.interpreter.ServerInterpreter.$anonfun$callInterceptors$3(ServerInterpreter.scala:35)
    at sttp.tapir.server.interceptor.RequestHandler$$anon$1.apply(RequestHandler.scala:16)
    at sttp.tapir.server.interceptor.log.ServerLogInterceptor$$anon$1.$anonfun$apply$2(ServerLogInterceptor.scala:22)
    at cats.effect.IOFiber.next$2(IOFiber.scala:398)
    at cats.effect.IOFiber.runLoop(IOFiber.scala:409)
    at cats.effect.IOFiber.execR(IOFiber.scala:1332)
    at cats.effect.IOFiber.run(IOFiber.scala:139)
    at cats.effect.unsafe.WorkerThread.run(WorkerThrea
```

This is either a bug in adopt-tapir, or in tapir itself - either way we need a way to reproduce this and fix somewhere

**Comment by micsza** [comment]
The issue was related to `sttp-model` bug that incorrectly invalidated a `Range` header of length one like `bytes=11-11`. Fixed with commit https://github.com/softwaremill/sttp-model/commit/8dc9b683e09549264cf680247d157c1d0b79bebd
