### ISSUE TITLE
[BUG] Fix problem with non-deterministic EOF Error

### ISSUE THREAD

**Issue by marcin-jozefowicz** [softwaremill/adopt-tapir#49]
It happens that the EOF error appears from time to time during working of the application.

Your task is to recreate and fix this error.

## Details

```
2022-06-28 04:38:53.482 CEST
02:38:53.478[1;33m [0;39m[io-compute-1] ERROR o.h.b.s.Http1ServerStage$$anon$1 - Error writing body
org.http4s.blaze.pipeline.Command$EOF$: EOF
Wrapped by: fs2.CompositeFailure: Multiple exceptions were thrown (2), first org.http4s.blaze.pipeline.Command$EOF$: EOF
 at fs2.CompositeFailure$.apply(CompositeFailure.scala:58)
 at fs2.CompositeFailure$.apply(CompositeFailure.scala:45)
 at fs2.Pull$.addError$1(Pull.scala:1143)
 at fs2.Pull$.viewCont$1(Pull.scala:1150)
 at fs2.Pull$.$anonfun$compile$22(Pull.scala:1187)
 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:932)
 at delay @ org.http4s.blazecore.util.EntityBodyWriter.$anonfun$writePipe$4(EntityBodyWriter.scala:83)
 at flatMap @ org.http4s.blazecore.util.package$.fromFutureNoShift(package.scala:40)
 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 at handleErrorWith @ fs2.Compiler$Target.handleErrorWith(Compiler.scala:160)
 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
 at flatMap @ fs2.Pull$.goEval$1(Pull.scala:1060)
```

Just before errors there are only request which need only static content of the page: 

```
02:38:52.246[1;33m [IXP-WWJ-GGA] [0;39m[io-compute-2] DEBUG c.s.a.h.HttpApi - Request: GET /embedded-form, handled by: GET /*, took: 1ms; response: 200
02:38:52.532[1;33m [SNI-VDL-ZIO] [0;39m[io-compute-2] DEBUG c.s.a.h.HttpApi - Request: GET /static/js/main.dc05fc37.js, handled by: GET /*, took: 1ms; response: 200
2022-06-28 04:38:52.590 CEST

controller
10.0.64.38 - - [28/Jun/2022:02:38:52 +0000] "GET /static/js/main.dc05fc37.js HTTP/2.0" 200 201812 "https://adopt-tapir.softwaremill.com/embedded-form" "Mozilla/5.0 (Linux; Android 12; SM-G973U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Mobile Safari/537.36" 125 0.060 [default-adopt-tapir-80] [] 10.0.33.105:8080 201812 0.060 200 8e6bc5ef0f2a4aa74724b4024ade446e
2022-06-28 04:38:52.619 CEST
```

**Comment by geminicaprograms** [comment]
The only meaningful reference that I have found is [here](https://github.com/http4s/blaze/issues/668)...
